version = "1.0.0.0"
version_code = "250505"
changelog = "EECT 1.0正式发布"
date = "20250505"
importance = "high"
file_name = "EECT_1.0.0.1.250509.1.-windows-x64.zip
download_url = "https://github.com/EECT/EECT/releases/download/v1.0.0.1/EECT_1.0.0.1.250509.1.-windows-x64.zip"