version = "1.1.0.0-b1"
version_code = "250520"
changelog = "本次测试版本更新内容如下：\n1.全新设置界面以及更全面的设置项（虽然大部分都还用不了）\n2.在设置中加了一点动画效果，使界面切换不呢么生硬，后续会在更多界面加上。\n\n注：设置的名言可以在Issues投稿哦。\n\n                     ——Lyang1273"