version = "1.1.0.0-b1"
version_code = "250520"
changelog = "本次测试版本更新内容如下：\n全新设置界面以及更全面的设置项（虽然大部分都还用不了）\n\n下一个bate版本预计更新内容：完善设置功能。\n\n----开发小作文----\n原本在520的时候就该发这个预览版本的，可谁懂电脑网卡偏偏在那一天出了问题，就没有得发……不过在521补上了。\n……你问我1.1正式版什么时候发布？等六月吧，当然不出意外的话。\n设置的名言可以在Issues投稿哦，祝各位521快乐！\n\n                     ——Lyang1273"